spring.main.banner-mode=off
spring.application.name=lightflare
server.port=8066
server.shutdown=graceful
server.forward-headers-strategy=framework

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.encoding=UTF-8
spring.jdbc.template.fetch-size=100

lightflare.auth.cookie.secure=true
