<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.lightflare</groupId>
		<artifactId>lightflare-parent</artifactId>
		<version>0.1</version>
		<relativePath>../../pom.xml</relativePath>
	</parent>

	<artifactId>lightflare-slack</artifactId>

	<properties>
		<slack-bolt.version>1.48.0</slack-bolt.version>
		<jakarta-websocket-client-api.version>2.2.0</jakarta-websocket-client-api.version>
		<tyrus-standalone-client.version>2.2.0</tyrus-standalone-client.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.lightflare</groupId>
			<artifactId>lightflare-tool-core</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>com.slack.api</groupId>
			<artifactId>bolt-jakarta-socket-mode</artifactId>
			<version>${slack-bolt.version}</version>
		</dependency>

		<dependency>
			<groupId>jakarta.websocket</groupId>
			<artifactId>jakarta.websocket-client-api</artifactId>
			<version>${jakarta-websocket-client-api.version}</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.tyrus.bundles</groupId>
			<artifactId>tyrus-standalone-client</artifactId>
			<version>${tyrus-standalone-client.version}</version>
		</dependency>
	</dependencies>
</project>
